# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Grep's personal site
email: grepcommandant@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Repositorio de artículos y guías de desarrollo, computación e informática.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://grepcommandant.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  grepcommandant

# Build settings
markdown: kramdown
